[book]
language = "en"
multilingual = false
src = "src"
title = "Software Requirements Specification for Slope Stability Analysis Program"
[output.html]
smart-punctuation = true
mathjax-support = true
