# This is the simple Travis configuration, which is intended for use
# on applications which do not require cross-platform and
# multiple-GHC-version support. For more information and other
# options, see:
#
# https://docs.haskellstack.org/en/stable/travis_ci/
#
# Copy these contents into the root directory of your Github project in a file
# named .travis.yml

# Use new container infrastructure to enable caching
sudo: false
dist: xenial

# Do not choose a language; we provide our own build tools.
language: generic

branches:
  except:
    - gh-pages

env:
  global:
    - secure: "zpSgEG8GvxOl8qJl+3OLiW7p5KdvzOOkC9g2ukLftmJ5cQUO2c7Zr7g/L/6ZQak96eDjyinV953laKXnrgy0BhZV1lnwPrnfEnvIV8BRkxIJ2XjMv3oNmwvAX5ayAKzeE7LBqeQyuFf83K+NP8QV5N432Ar9PryoJC5HvK4B/iQ1SuzWYcFSSuowNC1oukQUCKBVyzuhjv88VrZWqj2pLb7QgWlKNfokMsyYgNSytbu4A8xBn3zd51z2wgIjvfQlW9YnmENrloqPd4EcTnnjE+/2g4OSJ5ULWAu3n2QWmO5X5MhI7yGfQsH8fSR1pPSjw6iGYQ8G9woci5kyWCKCYZvYMUWUEZY6+vP+xhknRxkN9X/s9v6S9/Di2kKU0kOxcZC4p+9RF0NT3cZDzValhhRINAiprQYX8ri5G+BOq2fsKyENezvc+OuLvEHXhvskMuuZUJuWYB0ScUYooqIRgJE79Fr3d1EjDM0cQwFrMbOt6LF1P3wgPMo06Zy+4dfgqEx/heeKxX1yNFFbdd5WaSqhWac/7s4Y4v4UKHwbpKwZ1KjlW464VC/Dtwdwc/yS/iHRlcTdBjLl3MNdBA2sdxbDfsuao5osnCLdnt/qQ5B4cRpy3fJkbsmyNfLF57aE3bqpneUWHWrmbhgQ5PSRW6nyKpqgQkyzFD8B0WbfzIM="
    - secure: "OiCqBb3REAAkRLkynqsC9pN0K3b2oBAOCaFi2wGeeOMWbyql6PTUUaa1effRmb5l9llqVW3MN2g3iaFp3PjghQeoUIYPJnZ6QptR90j6L07UxQI/ZgEHyTYB3HKOxkHPeRk298HEvW36aFNik6Dmt6prnzElYsEeh6sPDiGYHO+cKWtvvUCM89qt9/aFcYE4Rn4Omr3+5uN62L/9Fi0XGKdnA+jORaqt6ARHYmycvqN407xHbvHQNun27ft1VOFLDCmOLFJJa7Nc462yy11DHKtLWcT3bj5oa1cK79o8Frp4KFSbZ8HXKFVz/AdR2fKCE/Iptek0TAJjR01YQOR6PcSrBbHiCMcZ83izyb6svourSJN30/wBxQwGedL7/f/p9NFOdF5AgK90Q+emQYDUDFXp6T4Sl1WFzV41wwdF6scfptrRLMYKNGm0QOxr8/TcyQk8GorlQM4NIOCGZRXx1oXcc2F3jXZ6vnbnGE0bl2m2vG1JYgdXCoTiCZbTJgJn6ZnfVT58JiVXzFCW9D9GPshMHwoTo/3CGfq1EObndyzwgiSgPgNFn58dT699Qu8DVlMgWcbMr+OGa+4hMGCpsD/qHF9qXmcZuJXaXo+T/Bua20a1ShAbP5OUT5ZcofI4N+N1QnxJv0N7pX1ts26fiWJV5OjE27sZP/Kt3X2yRew="
    - LABEL_FILE=/tmp/ci_build_failures
    - MANAGED_LABEL_FILE=/tmp/ci_managed_labels
    - ALL_FUNCTIONS_FILE=$(mktemp)
    - SHELL_OPTS_FILE=$(mktemp)

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

# Ensure necessary system libraries are present
addons:
  apt:
    packages:
      - libgmp-dev
      - python3
      - graphviz
# TeX Building
      - fonts-lmodern
      - texlive-bibtex-extra
      - texlive-latex-extra
      - texlive-math-extra
      - texlive-xetex
      - texlive-luatex
# Code Building
      - g++
      - default-jdk
      - mono-devel

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl --max-time 60 -sSL https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- source code/scripts/ci_functions.bash

install:
# Build dependencies
- stack --no-terminal --install-ghc test --only-dependencies --stack-yaml code/stack.yaml

script:
 - ci_export_funcs
 - cd code
 - >-
     ci_fstep "CI: HLint" "curl --max-time 60 -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s ."
 - >-
     ci_fstep "CI: Build" make prog stackArgs="--no-terminal" GHCFLAGS=-Werror
 - >-
     ci_fstep "CI: Stable" make stackArgs="--no-terminal" NOISY=yes
 - >-
     ci_fstep "CI: TeX" make tex SUMMARIZE_TEX=yes
 - >-
     ci_fstep "CI: Code" make code
 - >-
     ci_fstep "CI: Docs" make docs haddockArgs=\"--no-haddock-deps --no-haddock-hyperlink-source\"
 - >-
     ci_fstep "CI: Deploy" sh scripts/maybe_test_deploy.sh
 - python3 scripts/pr_label_update.py

deploy:
  provider: script
  skip_cleanup: true
  script: bash scripts/deploy_wrapper.bash
  on:
    branch: con_dep

notifications:
  email:
    - szymczdm@mcmaster.ca
    - carette@mcmaster.ca
    - smiths@mcmaster.ca
  on_success: change
  on_failure: always
